[package]
name = "lesson18_tcp_socket"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
build_html = "2.4.0"
lesson8_lib = { path = "../lesson8_lib" }
